channels:
  - anaconda
dependencies:
  - cython
  - python==3.7
  - numpy
  - pandas
  - pip:
    -Sphinx
    -sphinx-rtd-theme==0.4.3
    -sphinx-theme==1.0
    -sphinxcontrib-applehelp==1.0.2
    -sphinxcontrib-devhelp==1.0.2
    -sphinxcontrib-htmlhelp==1.0.3
    -sphinxcontrib-jsmath==1.0.1
    -sphinxcontrib-qthelp==1.0.3
    -sphinxcontrib-serializinghtml==1.1.4